CREATE VIEW POSTLATEST
AS
SELECT P1.PID,p1.usrid, p1.title,p1.description,P1.LNK,p1.posttime,p1.score, LC.LIKECOUNT, DC.DISLIKECOUNT
FROM POST P1,
(SELECT P.PID, COUNT(PL.PID) AS LIKECOUNT FROM
POST P LEFT OUTER JOIN POSTLIKE PL
ON P.PID = PL.PID
GROUP BY P.PID) LC,
(SELECT P.PID, COUNT(PD.PID) AS DISLIKECOUNT FROM
POST P LEFT OUTER JOIN POSTDISLIKE PD
ON P.PID = PD.PID
GROUP BY P.PID) DC
WHERE P1.PID = LC.PID 
AND P1.PID = DC.PID
ORDER BY P1.POSTTIME DESC;


CREATE VIEW POSTPOPULAR
AS
SELECT P1.PID,p1.usrid, p1.title,p1.description,P1.LNK,p1.posttime,p1.score, LC.LIKECOUNT, DC.DISLIKECOUNT
FROM POST P1,
(SELECT P.PID, COUNT(PL.PID) AS LIKECOUNT FROM
POST P LEFT OUTER JOIN POSTLIKE PL
ON P.PID = PL.PID
GROUP BY P.PID) LC,
(SELECT P.PID, COUNT(PD.PID) AS DISLIKECOUNT FROM
POST P LEFT OUTER JOIN POSTDISLIKE PD
ON P.PID = PD.PID
GROUP BY P.PID) DC
WHERE P1.PID = LC.PID 
AND P1.PID = DC.PID
ORDER BY P1.SCORE DESC;
